package com.maxtrain.tutorial.models;

public class Customer {
	
	private int id = 0;  //Java property syntax
	private String name;  //in Java String is a class so the string type has to be typed as shown. 
							//Use the class name; no alias.
	private double sales;
	
	public void Print() throws Exception {
		var trueOrFalse = true;
		if(!trueOrFalse) {
			throw new Exception();
		}
	}
	
	public void Debug() {
		try {
			Print();
		} catch(Exception ex) {}
	}
	
	public Customer(String name) {
		this.setName(name);
	}
	public Customer(String name, double sales) {
		this(name);
		this.setSales(sales);
	}
	
	public int getId() { 
		return id;
	} //Java method syntax; this is the getter method
	
	private void setId(int id) {
		this.id = id;
	} //this is the setter method

	//these getters and setters can be auto-generated by right-clicking open space in the editor
	//and selecting Source and clicking Generate Getters and Setters in the drop-down menu.
	public String getName() { 
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getSales() {
		return sales;
	}

	public void setSales(double sales) {
		if(sales < 0) {
			//do something here and return
		}
		this.sales = sales;
	}
	
	public Customer() {
		this.id = 1;
	}
}
